### ISSUE TITLE
Add support for comments within query body

### ISSUE THREAD

**Issue by nskerl** [datalust/seq-tickets#1010]
This is a pretty simple feature request to support both inline and multi-line comments within the query body. 
Using the general SQL convention, examples would include:

```
/* 
    Some explanation here
    Perhaps modification history 
*/
select count(Attribute1='abc' and Attribute2=99) as [SomeEventCount], -- additional comments here
       count(*) 
from stream
```

Thanks!

**Comment by nblumhardt** [comment]
Thanks for the nudge, Nathan, we've long wanted to add this 👍

**Comment by nblumhardt** [comment]
![image](https://user-images.githubusercontent.com/342712/90702105-ba4cf480-e2cd-11ea-9e4a-e2dce96eac5b.png)

Comments are supported in both SQL-style queries, and standalone filters.

We settled on SQL-style `-- to end of line` comments only, because of the ambiguity C-style comments introduce: `/* test */` would currently tokenize as a regular expression literal, so the risk of introducing parser bugs with a change, there, would be very significant.

**Comment by nblumhardt** [comment]
One note - thanks @larenelg - this does incur a small breaking change; `--1` will now be considered a comment, and `-(-1)` will be required for double-literal-negation.
