### ISSUE TITLE
Dashboard and Ingestion views show "flat line" even though events are arriving in the Events view

### ISSUE THREAD

**Issue by NameOfTheDragon** [datalust/seq-tickets#1012]
Hi. I've noticed an odd situation where the Dashboard and Ingestion pages don't tally with what I see in the Events view. I'm not sure whether this is a bug, a configuration issue or just bad expectations. The easiest way to explain it was to make a video, so here it is.
https://youtu.be/brNANuKliV8

Thanks,
Tim Long

**Comment by nblumhardt** [comment]
Hi Tim, thanks for the video explanation!

Just regarding your last query, in the _Ingestion_ view, the tiny sparkline charts are scaled against one another, so the volume coming from syslog is too small to see against the larger spikes from the GELF input earlier in the day.

We considered not scaling these, so that each input would show a more detailed profile of its activity, but this would mean that the top "overview" chart would not be the sum of the smaller charts. The jury is still out on whether this is the right approach, there's definitely a downside as you've observed.

The "last five minutes" dashboard flatline is more perplexing; I can't spot anything yet, but here are my working theories, in case one of them is a lucky guess:

1. The build is earlier than 2020.1.4292, and the condition attached to the chart is affected by one of a handful of query execution bugs present in the first 2020 builds; I think this is a long shot, but can't see the chart's condition nor the Seq version in the video (the full version is under the _Support_ menu); updating to 2020.1.4292 is worthwhile anyway
1. The Seq server's clock is off; if its clock is incorrect, its notion of the "last" five minutes may not be right
1. The timestamps on the incoming events are off; that might place them outside the last five minutes, even though they show in the _Events_ view; I checked by eye and I can't find any evidence that this would be the case, however
1. There's some issue in the chart's conditions; it would be great to see the `where` clause etc, and signals attached to the chart, as well as a zoomed out "last hour" or "last day" view to determine whether the problem is temporal or whether the entire chart is flat back into the past

Hope this narrows it down! Thanks,
Nick

**Comment by nblumhardt** [comment]
We've reviewed the various trade-offs being made in how we scale the per-input charts in the ingestion view, and think we'll leave this as-is for the time being. Thanks for the feedback on this, @NameOfTheDragon 👍
