### ISSUE TITLE
Saving dashboard reverts changes

### ISSUE THREAD

**Issue by CrossBound** [datalust/seq-tickets#1054]
I created a new dashboard and when trying to save changes to my layout/configuration hitting save will revert my changes for some reason. Can't seem to get it to actually save every time although sometimes it works. Check out the attached video of the occurrence.

Thanks.
[Seq Save Error.zip](https://github.com/datalust/seq-tickets/files/5503785/Seq.Save.Error.zip)

**Comment by larenelg** [comment]
Hi David,

Thanks for raising this one!

I've had a quick look but couldn't quite reproduce your issue consistently (though I was able to reproduce it a few times!). Can I ask, if it only happens when you set it to 2 columns during that session?

A temporary workaround (and definitely not ideal) is to fully refresh Seq after you've hit this strange behaviour. And stick >= 3 column widths. 

Leave it with us and we'll dig deeper in the next day or two.

**Comment by nblumhardt** [comment]
This is a regression caused by https://github.com/datalust/seq-tickets/issues/1022
