### ISSUE TITLE
Automatic hyperlinks for urls in log event context properties

### ISSUE THREAD

**Issue by laurencee** [datalust/seq-tickets#1114]
Hello,

After using Seq for a while at various places I feel like it'd be a nice improvement if urls were automatically converted to hyperlinks in context properties. I have found it to be quite common that I make use of context properties to link to external places related to a log event.

I'm not sure of the negatives of doing something like this but it would improve my user experience by not having to select urls out of the text fields and open them in a new tab (making sure I selected all the text for the link and what not).

Maybe this could be extended to the messages as well? That could cause some issues with attempting to expand a log event however which is why I'm being specific to context properties.

Let me know your thoughts!

**Comment by nblumhardt** [comment]
Thanks for the note, Laurence! We've considered this in the past - we're just a little uneasy about the implications for security; even if we mark the links `rel="noopener noreferrer"`, it still seems like having clickable URLs that could come from untrusted sources in the UI is questionable. (E.g. a malicious user might enter the URL as their Name in a web form, which would result in a hyperlinked value in the Name property if logged.)

Moving to a discussion, since we're now tracking uncommitted features over there :+1:
