### ISSUE TITLE
Prefer AM/PM time formatting - Formatting issue?

### ISSUE THREAD

**Issue by ryanbuening** [datalust/seq-tickets#1376]
**Describe the bug**
When Prefer AM/PM time formatting is selected, the dates are formatted strangely after the initial entry.

![image](https://user-images.githubusercontent.com/812974/141691254-36afde36-52cb-4aff-90c1-975a4104f629.png)

![image](https://user-images.githubusercontent.com/812974/141691266-d0f8c0fe-9d29-44dd-9d31-137a0946b923.png)

**Comment by liammclennan** [comment]
Hi @ryanbuening,
Thank you for the bug report. This should be fixed in the next release.

Until then, it is the combination of 'Prefer AM/PM time formatting' + day month year dates + times with two-digit hours that causes the formatting problem. Your options are to disable 'Prefer AM/PM time formatting' or enable 'Prefer yyyy-MM-dd date formatting'. Either of those options should fix the problem for now. 

Thanks again!

**Comment by liammclennan** [comment]
Quick follow up @ryanbuening, 

Another option for you is to fix the formatting with some custom css. On the Settings > Instance page enter the following in the 'Style overrides' text area and save:

```
.event-list .event .timestamp { 
  width: 175px;
}
.event-list .event .description { 
  padding-left: 180px;
}
```

That should fix the formatting for you.
