### ISSUE TITLE
Highlighting within search results

### ISSUE THREAD

**Issue by andrewtobin** [datalust/seq-tickets#144]
Instead of just filtering, also offer the option to highlight a view/query/filter - so it doesn't get a subset of the rows, but highlights either on the date field, or the row background by color.

This would allow you to flag certain events you're looking for, but also in the context of the rest of the feed of the view you're looking at.

It would be good if you could be able to set up multiple highlights by color, and if it had the same view/query setup as the filters.

**Comment by nblumhardt** [comment]
Moved to: https://seq.uservoice.com/admin/forums/268188-general/suggestions/6976212-use-expressions-to-highlight-rather-than-filter - thanks!

**Comment by nblumhardt** [comment]
Reopening, I think it'd be great to do this; some minor UI reorganisation coming in the next version, will see if it fits in there...

**Comment by nblumhardt** [comment]
A great sketch of how this might work: http://docs.getseq.net/v3/discuss/57a3b6098d35f91900970c4b

**Comment by nblumhardt** [comment]
Another suggestion, via `#hastags`: http://docs.getseq.net/v3/discuss/57ad1454faa7a10e00449526

**Comment by nblumhardt** [comment]
The underpinnings of this feature could also be used to highlight the "original" event when searching for adjacent events (_Id_ > _Find with adjacent_). At the moment it can be tricky to spot the original event in among the "adjacent" ones, otherwise.

**Comment by nblumhardt** [comment]
This has been open a long time and not moved forward, so we're going to close it, despite hoping that we'll cover this with a new, more flexible version of "columns", in a future version. Thanks everyone for your ideas!

**Comment by jbennink** [comment]
That's a pity. I jus tfound this before openening a new issue. My workflow is often, find the "errors" and then zoom in. This is a frustrating workflow.

1. Filter on "Error"
2. Look through, select 1 and do a +- 5 seconds
3. Then unchek the "Errors" loglevel filter t oreveal everything in that time-window <=frustration 1
4. Since we log a lot (mostly Trace by default) find the error in that 10 seconds time-window. Then that small red circle in the log line is not that handy. Also it requires scrollen and since scolling is endless PdDn-ing requires Seq to pull in more data. <= frustration 2 (scrolling with more data coming in is slower)
5. Find the log lines before the error. Hmmm Yeah that seems something. Lets see whether the other  errors are the same.
6. Reset the time-range filter, reapply the error filter, scroll to the next error.
7. Rinse and repeat (sigh)

This make me long for the olden days where I could open a 100MB log file in Notepad++ and Find my way to success [which obviously has other disadvantages]

So after that setup. When You could Hightlight what you filter on instead of filter out anything else you could scroll though, or perhaps do a skip to the next "filter match". 
I saw something like this in wireshark where you can hightlight specific packets while you scroll thought the capture

**Comment by KodrAus** [comment]
In the new metrics UX we've been working on we've ended up with the concept of pinning; charts of interest can be pinned so they always appear at the top of the list, and remain even when your filter changes. Something like this for events where the events you pin always appear at the top of the screen if they're later than your current window, or below if they're earlier, might really help smooth out that UX there

**Comment by jbennink** [comment]
Not sure whether pinning events would help. I always struggle with systems that allow you to 'pin' stuff to the top.

In Wireshark you can color specific lines based on the information in that line so they stand out in the capture. This allows multiple colors so you can 'tag' traffic on port xxxx as green and then also traffic that does icmp as blue and traffic from ipv4 a.b.c.d as red. You get a good feel for what traffic is flowing in the capture and can scroll quickly where this colors are constantly applied.

**Comment by KodrAus** [comment]
That sounds like a different feature than highlighting specific events within a diagnostic session to easily refer back to them, but I can also see that as being useful. It’s somewhat covered by columns, except columns don’t visually distinguish their actual values through colour.

We _kind_ of do something along these lines with the service name now I think using a coloured strip in the far left of the screen. We could consider something like an “accent expression” for events that’s like a column, but determines the colour of the strip on the event.
