### ISSUE TITLE
Docker hub readme `Supported tags` section doesn't include newer versions and still includes `preview`

### ISSUE THREAD

**Issue by AKTheKnight** [datalust/seq-tickets#1573]
**Describe the bug**
Docker hub readme `Supported tags` section doesn't include newer versions and also still includes `preview`

**To Reproduce**
1. Go to 'https://hub.docker.com/r/datalust/seq'
3. Scroll down to 'Supported tags'
4. See `latest, 2020.1, and preview`

**Expected behavior**
1. Maybe some 2021 and 2022 tags in there too?
2. `preview` no longer appears to be available, should it be removed?

**Screenshots**
![image](https://user-images.githubusercontent.com/7502848/169651609-a38cfc0c-7244-425c-b6bb-114c78b48013.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Seq Version: N/A
 - Using Docker? Yes

**Additional context**
Seq is awesome

Edit: Added about `preview` no longer appearing to be available

**Comment by KodrAus** [comment]
Hi @AKTheKnight :wave: Thanks for pointing this out! The docs there are just for example, so they haven't been updated as Seq versions have moved forward. You can find the full list of tags in Docker Hub by checking [the _tags_ tab of their UI](https://hub.docker.com/repository/docker/datalust/seq/tags).

I've gone and updated the readme to call out that we're talking about the general versioning scheme rather than the exact set of possible tags. :bow:
