### ISSUE TITLE
Accept an explicit EventType when events arrive at the logging endpoint

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#161]
Currently Seq always infers the event type by hashing the message template. When a non-structured logger (e.g. log4net, NLog) is used, the event type is thus pretty much random. 

When events are sent by these loggers, Seq should accept the event type explicitly in the JSON document; this way, e.g. `$00000149` might be "log4net" and `$00009106` might be "NLog" - this in the long run will make it easier for Seq to reliably do smart things based on event types.

**Comment by tzographos** [comment]
I'm experiencing exactly the same issue on Seq 2020.1. I am seeing thousands of different event types, even though they should be treated as unique.
My setup is:  Application -> Serilog -> Sqelf -> Seq

I have enriched the log messages (from within the application) a new property named "EventType". The property values are indeed unique, but are disregarded by Seq.

**Comment by nblumhardt** [comment]
Hello! Thanks for the note. The event type in question here is part of the underlying event format, and not based on an `EventType` property attached to the event. Unfortunately there's no way to transmit that info through GELF/Sqelf, the _Serilog.Sinks.Seq_ sink would be needed for this.

**Comment by tzographos** [comment]
Therefore, am I correct in assuming that Sqelf (Seq.Input.Gelf) transmits the log events to Seq by making replacements to the message template using the actual property values (and thus leading to non-unique event types in Seq)? 

Example flow:
App sends to Sqlef: "@mt":"Hello {Receiver} !", "Receiver":"World" ...       -->hash:ABC (unique)
Sqelf sends to Seq:  "@mt":"Hello World !", "Receiver":"World" ...            -->hash:XYZ  (non-unique)

And some additional questions:
a) what are the implications in Seq's performance when using a multitude (possibly millions) of different event types?
b) Since periodic batching relies on HTTP, which has its limitations from a performance standpoint, is there a way to transmit directly to Seq using a UDP ingestion port?

**Comment by KodrAus** [comment]
Hi @tzographos :wave:

> Therefore, am I correct in assuming that Sqelf (Seq.Input.Gelf) transmits the log events to Seq by making replacements to the message template using the actual property values (and thus leading to non-unique event types in Seq)?

The `sqelf` server doesn't render the message template itself, if you're using the `Serilog.Sinks.Graylog` sink to send your events to `sqelf` then that's where the replacement will be happening.

> what are the implications in Seq's performance when using a multitude (possibly millions) of different event types?

For 2020.1 there isn't any implication for performance. It uses the event type like an identifier for a callsite in your source, so having event types can help you link events to statements in source easier, but it won't have an impact on how Seq stores event data.

> Since periodic batching relies on HTTP, which has its limitations from a performance standpoint, is there a way to transmit directly to Seq using a UDP ingestion port?

If it's possible in your environment, since you're already using `Serilog`, I think you'll have the best experience using the `Serilog.Sinks.Seq` package and send events directly to Seq. It also participates in dynamic level filtering. It does use HTTP, but if you do run into any performance issues with it then we should definitely try work through them!

**Comment by tzographos** [comment]
Hello KodrAus,

A typical behavior I am experiencing on a container with 4GB RAM and 3 vCPUs using periodic batching is this:
![image](https://user-images.githubusercontent.com/12127636/88189510-cf3c5680-cc41-11ea-93fa-47329848ad0a.png)

The average ingestion rate should be around 0.5k~2.0k events/minute depending on the time of day. Also experiencing many "invalid payloads" (around 100 in the last 24hours) with OutOfMemory exceptions. 

I will be reverting to ```Seq.Inputs.Gelf``` for the moment, since HTTP performance will impact the app (next step: RMQ). I know will be seeing thousands of different event types (due to the rendering of the template as you pointed out). 
As mentioned, I'm enriching the log events with an additional ```EventType``` property (basically, a Murmur3 hash of the template), but it would be nice if Seq could somehow be configured to use the EventType of the message instead.

**Comment by nblumhardt** [comment]
Hi all! Just adding some thoughts, here:

I think we should close this ticket again; it was implemented as planned a long while back, so the thread here may be confusing from that standpoint.

Mapping a property on the event to an explicit event type in Seq would be a new feature, which would belong on _Seq.Input.Gelf_, but would need some design work in order to be general enough to be useful, so could be some time away. Worth thinking about but probably not useful in the very short-term.

0.5 to 2 k events/minute should be trivially achievable with Seq and HTTP on that server spec, though; it sounds like something is going wrong somewhere in the stack - perhaps we move this to a support thread and try to work out why the ingestion is failing? If so, emailing support@datalust.co would kick that off, @tzographos .
