### ISSUE TITLE
Restore  seq from backup pvc in the kubernetes

### ISSUE THREAD

**Issue by jonasmulticloudiac** [datalust/seq-tickets#1621]
Hello Guys, 
I've tried to recover seq from backup in my storage.

Steps :

1- I Created a new PVC and recovered a copy of Seq  my bkp  I used this  tool commvault '...'
2- Mount PVC with the data of backup'....'
3-  Starting Seq2 with another deploy on my Kubernetes pointing to new PVC...'
4- But when I started the new seq I didn't see the logs between the dates.

**Screenshots**
![image](https://user-images.githubusercontent.com/76959306/180238462-62419495-9224-4fc4-8cfc-f52805279459.png)

** Inside de Pod **
![image](https://user-images.githubusercontent.com/76959306/180239885-65c1a175-11f7-499f-9d4f-785872675cd3.png)

How could I  fix this 
Thanks

**Comment by KodrAus** [comment]
Hi @jonasmulticloudiac 👋 

Hmm, I’m not familiar with commvault. Does it perform backups by snapshotting your volume?

It looks like your new volume has ended up with a lot of `.junk` files in it. That happens when Seq spots a file in your `Stream` directory that it doesn’t have internal metadata for. The metadata is stored in the `.metadata` file, which you have sitting there. You can end up with all files being marked as junk if the `.metadata` file isn’t copied into the new location so Seq creates an empty one on startup.

If you tried to run the process again I’d be curious to see if it did the same thing again.

**Comment by nblumhardt** [comment]
Hi @jonasmulticloudiac ; I'll close this as stale assuming you were able to move ahead, but if you need any further assistance with it, please just let us know.

Best regards,
Nick
