### ISSUE TITLE
seqcli signal import --merge doesn't respect the signal id

### ISSUE THREAD

**Issue by danielloczi** [datalust/seq-tickets#1718]
**Describe the bug**
I created a newline-delimited JSON file which contains some signals to create or update. When I import the signals from that file using seqcli signal import command using the --merge argument, and Seq server has no signal with a matching id, then the id defined in the json file is ignored, and the new newly generated signal gets a new id.
This results, that running the very same command again instead of updating the existing signal, it always generating new ones.

**To Reproduce**
1. Start with a freshly install Seq or use docker to start a new one:
`docker run --name seq -d --restart unless-stopped -e ACCEPT_EULA=Y -p 5341:80 datalust/seq:latest`
3. Generate a new Api token with all of the permissions
4. Generate a simple signals.json file, like:
`{"Title": "TEST signal1", "Description": "", "Filters": [{"Description": null, "DescriptionIsExcluded": false, "Filter": "AppName = 'App1'", "FilterNonStrict": "AppName = 'App1'"}], "Columns": [], "IsProtected": false, "Grouping": "Explicit", "ExplicitGroupName": "AppName-test", "Id": "signal-1001"}
{"Title": "TEST signal2", "Description": "", "Filters": [{"Description": null, "DescriptionIsExcluded": false, "Filter": "AppName = 'App2'", "FilterNonStrict": "AppName = 'App2'"}], "Columns": [], "IsProtected": false, "Grouping": "Explicit", "ExplicitGroupName": "AppName-test", "Id": "signal-1002"}
`
5. Import the signals from the file using the command:
`docker run -v $pathToSignalsJson:/data --rm datalust/seqcli signal import -s $seqServer -a=$apiKey --merge -i=/data/signals.json`
6. Observe, that the signals are created.
7. Check the id of the newly created signals: Select the signal, and hit Edit as JSON.
8. re-run the import command (see: step 4.)
9. Observe, that instead of updating the existing signals, new signals are created

**Expected behavior**
When importing the signals using the --merge argument, the ids should be respected, and if no signal is found in the Seq server with a matching id, then the new signal should be generated with the id defined in the json file (signal-1001, signal-1002 in the example).
If re-run the import command with --merge argument, then don't create new signals, just update them (because I expect that they are already created with the id I defined)

**Environment (please complete the following information):**
 - OS: Linux
 - Browser: Chrome (but doesn't matter)
 - Seq Version: 2021.4.7192, 2022.1.7921
 - Using Docker? Yes

**Comment by nblumhardt** [comment]
Hi Daniel, thanks for reaching out!

Seq doesn't support specifying ids for new items (via the API or otherwise) so this isn't possible today, unfortunately. Ids in the source JSON file are always ignored when creating new items.

The `seqcli template export` and `seqcli template import` commands are an updated/improved version of the `signal import` mechanism that will avoid creating duplicates, though. The `seqcli template import`'s `--merge` option matches by name, so you should be able to run imports multiple times and not see duplicates.

Template import also generates a mapping `.state` file that is more precise and manageable than the `--merge` option; check out:

https://blog.datalust.co/copying-signals-and-dashboards-using-seqcli-templates/

for an overview, but please let me know if you give it a try and need any help!

Best regards,
Nick

**Comment by danielloczi** [comment]
Hi @nblumhardt!
The suggested solution with template import solved my problem! Works as expected! 
Cool! Thanks!

**Comment by nblumhardt** [comment]
😎
