### ISSUE TITLE
Update CSP to deny `unsafe-self`/`unsafe-inline`

### ISSUE THREAD

**Issue by MattWorkWeb** [datalust/seq-tickets#1725]
We have seq service running in docker container in Kubernetes cluster with a web endpoint/url.  When our security scanner scans the Seq server URL, we are getting a low/unacceptable score due to the content-security-policy control:
![image](https://user-images.githubusercontent.com/15264334/208466575-d11cfd7f-a108-4563-b34e-2b9f86d8b287.png)
Are there configuration options in Seq server to improve this?  Is there any documentation on how to configure for improvement.

Thank you.

**Comment by liammclennan** [comment]
Hi @MattWorkWeb ,

Thank you for the report. 

There is no configuration of content-security-policy, except https://docs.datalust.co/docs/json-config#apiframeancestors which is probably not what your tool is objecting to. 

We will investigate and see if the CSP can be improved.

**Comment by nblumhardt** [comment]
Hi again! In 2023.1 Seq's CSP has been updated to deny unsafe eval/unsafe inline scripts.

The obsolete `X-XSS-Protection` header has been removed (orange warning icon in your report above).

Unsafe inline CSS is not yet denied, due to some third party dependencies currently requiring it, but it's on our radar. Inline CSS should be somewhat less problematic than inline script, so we're considering these changes as a pretty decent win this time around :-)

Thanks for raising this!

**Comment by nblumhardt** [comment]
@MattWorkWeb the `datalust/seq:2023.1.8731-pre` image on Docker Hub includes this change, in case you have an opportunity to try it out. HTH!
