### ISSUE TITLE
Need help with the Filter command, while ingesting logs

### ISSUE THREAD

**Issue by sukesh-y** [datalust/seq-tickets#1812]
Hello Team,

I'm trying to ingest logs into **Seq** using `seqcli`. 
The logs are in a _.txt_ file and this is the format.

````
25544 11:28:40 WARN  The "SessionExpirationThreadCount" setting contains an invalid value. The default value is used instead. Invalid value: "". Default value: "8"
79084 11:28:40 WARN  Runner started: DatFilesLoaderAsyncRunner
43972 11:28:40 INFO  HttpModule is being initialized
43972 11:28:41 DEBUG The "Pipelines.Profiling.Enabled" setting is not defined in the configuration files. The default value is used instead. Default value: "False"
````

Let's say, I want to view only the "Warnings". So, to save the ingestion time, I want to ingest only those log entries.

The following queries did not work, meaning, no logs were ingested and no errors too.
`seqcli ingest -i D:\log.txt -x "{Thread:nat} {@t} {@l} {@m:*}{:n}{@x:*}" --filter="@Level='WARN'"`
`seqcli ingest -i D:\log.txt -x "{Thread:nat} {@t} {@l} {@m:*}{:n}{@x:*}" --filter="@l='WARN'"`
`seqcli ingest -i D:\log.txt --filter="@Level='WARN'" -x "{Thread:nat} {@t} {@l} {@m:*}{:n}{@x:*}"`
`seqcli ingest -i D:\log.txt  --filter="@l='WARN'" -x "{Thread:nat} {@t} {@l} {@m:*}{:n}{@x:*}"`

But this works:
`seqcli ingest -i D:\log.txt -x "{Thread:nat} {@t} {Level} {@m:*}{:n}{@x:*}" --filter="Level='WARN'"`
`seqcli ingest -i D:\log.txt --filter="Level='WARN'" -x "{Thread:nat} {@t} {Level} {@m:*}{:n}{@x:*}"`

1. I realized that the placement/position of `--filter` command is irrelevant. I mean it can be before or after `-x`. Is that correct?
2. The text argument 'WARN` is case sensitive, because 'Warn'` doesn't work. Is that correct? 
    I wish this wasn't case-sensitive.
3. My concern with the successful ingestion is, all the entries in Seq are now with the Level "Information" and thereby have same color. So, user cannot distinguish at the first glance, if the logs are of 'WARN' or 'ERROR' or 'INFO'. Because all have the same color.

![image](https://user-images.githubusercontent.com/24619393/229685741-a2b24e42-db70-487d-9f41-2887694d752a.png)

This is happening because, in the working queries, I have the `name` as "Level" and this is not the same as "@l". 
Why are these 2 conditions not working - `@l='WARN'` or `@Level='WARN'`
Is that how it is, or is there a different way to achieve this.

4. How to pass the `or` condition, say I want to ingest logs of warn or debug, and this doesn't work.
`seqcli ingest -i D:\log.txt --filter="Level=('WARN' or 'DEBUG')" -x "{Thread:nat} {@t} {Level} {@m:*}{:n}{@x:*}"`

Thank you

**Comment by KodrAus** [comment]
Hi @sukesh-y :wave:

The position of the argument doesn't matter, it'll run at the same point in the pipeline wherever it appears.

When extracting the level using the built-in `@l` name or `:level` type then the matching will be case-insensitive, otherwise it will faithfully retain the case of the property you. You can try a pattern and filter like this:

```
seqcli ingest -i D:\log.txt -x "{Thread:nat} {@t} {@l} {@m:*}{:n}{@x:*}" --filter="@Level='Warning' or @Level='Debug'"
```

The filter you write in `--filter` should match a filter you can write in Seq itself.

Hope that helps!

**Comment by sukesh-y** [comment]
Hello @KodrAus 

Thank you for the reply.

This is a sample section of my log.txt file, where Seq could not parse I guess.

![image](https://user-images.githubusercontent.com/24619393/229975304-a15543af-14ba-4daa-b6f0-145c2554d6e9.png)


When I execute this command, then there is no error, but also no ingestion.

![image](https://user-images.githubusercontent.com/24619393/229974737-4be83972-5442-4faf-b584-bce172c3186a.png)

And when I execute this command, there is an error:

![image](https://user-images.githubusercontent.com/24619393/229975178-728cf322-c7b0-4b7b-9c3c-4a3812b52b72.png)

Please advice.

Thank you

**Comment by KodrAus** [comment]
It looks like the filter still matches on the exact text like `WARN` rather than the transformed one like `Warning`. I've opened https://github.com/datalust/seqcli/issues/280 to track it.

In the meantime, you should be able to use an API key in Seq to filter out the non-warning events. This will still require parsing and transmitting them over the network, but they'll be immediately dropped by Seq. If you create an API key with a `@Level = 'Warning'` filter:

<img width="635" alt="Screenshot 2023-04-06 075628" src="https://user-images.githubusercontent.com/6721458/230221648-9c90b8fa-d5f7-4daa-ad57-f5a4ef5e653c.png">

and then ingest using an extraction pattern like:

```
seqcli ingest -i log.txt -x "{Thread:nat} {@t} {@l:level} {@m:*}{:n}{@x:*}" -a "YOUR API KEY VALUE"
```

then you should see only warnings ingested.

**Comment by nblumhardt** [comment]
The 2023.1.9225 (or later) build that we'll publish next week includes an improved `seqcli ingest` filtering experience. Hope this helps!
