### ISSUE TITLE
Seq is logging date into the future

### ISSUE THREAD

**Issue by neman** [datalust/seq-tickets#1878]
**Describe the bug**
Seq logs events into the future. 

The date is 15. December 2040 instead current date.

**Expected behavior**
Date should be correct date, at the moment of writing this bug it is 26. June 2023

**Screenshots**
![image](https://github.com/datalust/seq-tickets/assets/350314/dec28fe2-a313-4159-bf03-b6177d3eb707)

**Environment (please complete the following information):**
 - OS: Windows
 - Seq Version 2023.1
 - Using Docker? No

**Comment by KodrAus** [comment]
Hi @neman :wave:

By default Seq will respect whatever timestamp events are logged with, which might be different than the time Seq observes the event. This typically happens if the logging source has a skewed or misconfigured clock.

You can tell Seq to ignore the timestamp on events and use the arrival time [by setting _Use server timestamps_ on an API key](https://docs.datalust.co/docs/api-keys#server-timestamps), and using that API key when logging from that source.

Hope that helps!

**Comment by nblumhardt** [comment]
As of 2022.1, far-future timestamps should be being rejected by default: https://github.com/datalust/seq-tickets/issues/1570

@neman would it be possible to please share the output of:

```
seq config get -k storage.maximumFutureTimestampDriftSeconds
```

at an administrative PowerShell prompt on your Seq server machine?

If the value is reported as null/empty, you can configure it using:

```
seq config set -k storage.maximumFutureTimestampDriftSeconds -v 3420
```

(This will set a maximum 57-minute future drift.)

Thanks!

**Comment by nblumhardt** [comment]
Hi @neman; is this issue still causing problems for you? If not, please just let me know and we'll close it (or if so, we can check it out based on the info I mentioned above). Thanks!

**Comment by neman** [comment]
I will check with DevOps and let you know.

**Comment by nblumhardt** [comment]
Closing for now, assuming this is no longer an issue, but please let us know if not :-) Thanks!
