### ISSUE TITLE
Feature request: Limit concurrent user searches

### ISSUE THREAD

**Issue by DanAvni** [datalust/seq-tickets#1884]
I got alerts today from my monitoring system that Seq VM was using 100% CPU. When investigating I saw that a user has ran 5 separate queries (each on a different tab and probably spanning long time ranges). Since that user is killing performance for all other users at the same time, I suggest adding a limit on how many queries can execute for a user. The rest are queued and will be executed when one of his slots is available

**Comment by KodrAus** [comment]
Hi @DanAvni :wave:

Thanks for the suggestion :+1: Seq does actually have a limit on concurrent queries that works basically as you describe it, but it's a system-wide rather than a user-wide limit. We have discussed some approaches to better manage server resources under heavy query load that should cover this case as well as other similarly shaped ones.

**Comment by KodrAus** [comment]
Just following up through some triage; Seq has its system-wide query limit to cover this.
