### ISSUE TITLE
Install apps from Azure Artifacts feed

### ISSUE THREAD

**Issue by liammclennan** [datalust/seq-tickets#1916]
Nupkgs from pkgs.dev.azure.com can't be installed because the server redirects (to *.blob.core.windows.net in at least one case) and Seq does not follow the redirection. 

Investigate allowing packages to be installed even if the server issues a redirect.

**Comment by liammclennan** [comment]
The same issue appears to exist with the github package repository https://github.com/datalust/seq-tickets/issues/1974

**Comment by per-samuelsson** [comment]
> (to *.blob.core.windows.net in at least one case)

FWIW, the redirect from the GitHub package repository matches that pattern too. A fix for redirects would obv be general though, but yeah, shared because I had the info. 🙂

**Comment by liammclennan** [comment]
Thanks @per-samuelsson 

Good to know!

**Comment by nblumhardt** [comment]
Reclassifying this as a bug, the functionality's broken, even if it's due to changes in the source systems. We'll try to get this one sorted out 👍

**Comment by nblumhardt** [comment]
We've investigated rolling this out in a 2023.4 patch, but because the change needs testing and validation in the field, it's not ready to go into an RTM build, so we've decided instead to target the upcoming 2024.1 preview (and later 2021.4 RTM).

The change has been made internally now; I'll close this and update the milestone, and also leave a note here once a preview build is published to datalust.co and Docker Hub.
