### ISSUE TITLE
AutoComplete issues

### ISSUE THREAD

**Issue by DanAvni** [datalust/seq-tickets#1991]
1. AutoComplete does not suggest @Document
2. See attached video. When writing an expression like Version='a' and Source='b', AutoComplete works when typing "Version " but does not suggest anything when writing "Source" (In the video when the line shows "So" I was pressing CTRL+SPACE to try and show AutoComplete)

https://github.com/datalust/seq-tickets/assets/4114116/e6be42b5-2236-4b8e-8b6c-07e31c21763d

**Comment by nblumhardt** [comment]
Thanks for the heads-up, Dani, we'll have to take a look 👍 

I think the absence of `@Document` is due to it being largely obsolete; under the hood it expands to `ToJson(@Data)`, which is a better representation of what's going on (and communicates the likelihood of poor performance when running large queries over `@Document`).

**Comment by DanAvni** [comment]
Trying to be as backwards compatible as possible but I do understand the need to communicate the slow performance, maybe @DocumentJson? when I start typing @Document I will be prompted by the autocomplete so I do not have to remember the whole syntax for ToJson(@Data)

**Comment by nblumhardt** [comment]
I've just realized that this is likely the original report of #2138, which we just fixed in 2024.2. I'll move this to that milestone and mark it fixed.

Thanks for the feedback on `@Document`, we'll keep it in mind but currently plan to leave `ToJson(@Data)` as the syntax for this.
