### ISSUE TITLE
The Seq logo is no longer a link on the events page

### ISSUE THREAD

**Issue by xt0rted** [datalust/seq-tickets#2075]
**Describe the bug**

In a more recent version the link on the Seq logo was changed so when you're on the events page it's `ng-href` and `href` attributes aren't set. This means I can't middle click to open a new instance to run a secondary search for what I'm investigating.

Now I have to use one of the nav links like `dashboards` and then navigate back to the events page. Lots of needless steps just to get a new tab to query on a single correlation id I just pulled out of my main search.

**To Reproduce**

1. Middle click the logo while on the events page
2. Nothing happens...

**Expected behavior**

To open a fresh events page in a new tab like used to happen.

**Environment (please complete the following information):**

 - OS: Windows
 - Browser Chrome
 - Seq Version 2024.1.10981, though I think it started back with the new date picker update
 - Using Docker? Yes

**Additional context**

If you middle click on the find option a new tab opens, but it doesn't search for the given value which is one of the reasons I just middle click on the logo to get a new tab. It's quicker and easier than any other method.

![image](https://github.com/datalust/seq-tickets/assets/831974/fb33b98a-3dd8-4d0c-aee9-271edbef4e04)

**Comment by liammclennan** [comment]
Hi @xt0rted

What about right clicking on the browser tab and 'Duplicate'?

**Comment by dkearsley89** [comment]
I'd also like this link restored... I often use it as a quick way to reload SEQ to the default view (i.e clear signals, searches etc).

Side Note: The link is present on other pages (i.e Dashboards) it just doesn't work on the Events page.

**Comment by nblumhardt** [comment]
Hi! This one came about because the old link here (`#/events`) had the unexpected side-effect of clearing your filters/signals etc in Events, once we implemented full route-driven back button support a few releases ago.

We've come up with a workable fix; from the next patch this link will include all of the current route parameters if you're in Events; this should lead to a pretty nice middle-click experience:

![image](https://github.com/datalust/seq-tickets/assets/342712/bbf2e6e3-2e1f-4947-b4b8-5035511c3c7a)

On the other screens the link will remain the simple `#/events` one.

Cheers,
Nick

**Comment by nblumhardt** [comment]
Fixed in 2024.1.11001, published now :-)
