### ISSUE TITLE
The Individual license only permits one browser tab to access Seq

### ISSUE THREAD

**Issue by JamesG3D** [datalust/seq-tickets#2261]
**Describe the bug**
The Individual license only permits one browser tab to access Seq

**To Reproduce**
1. Go to http://localhost:5431/#/events
2. Go to http://localhost:5431/#/events in another tab
3. Go to http://localhost:5431/#/events in another tab
4. See error "The Individual license only permits one user to access Seq"

**Expected behavior**
The Individual license permits one user to open more than one browser tab to access Seq

**Screenshots**
![image](https://github.com/user-attachments/assets/293eb615-9493-41dd-a862-60c822e100a6)

**Environment (please complete the following information):**
 - OS: Windows, docker desktop, image: datalust/seq:latest 
 - Browser: any/all
 - Seq Version 2024.3.12021
 - Using Docker? Yes

**Comment by nblumhardt** [comment]
Hi James, thanks for the heads-up!

If you enable authentication (Settings > Users), the message will go away and shouldn't reappear. Authentication is a very good idea regardless, so that's the best way to resolve the problem.

More than one tab is certainly (intended to be) supported by the Individual option though; I'm not sure what might cause this behavior for you so we'll take a look :-)

**Comment by KodrAus** [comment]
It looks like it is possible to trip the usage check with 3 tabs. The solution here is to enable authentication (which is available in the individual license) which disables the tab limit.
