### ISSUE TITLE
TLS 1.0 and TLS 1.1 needs disabling on SEQ server as requested by security team

### ISSUE THREAD

**Issue by john-duff** [datalust/seq-tickets#2330]
TLS 1.0 and TLS 1.1 needs disabling on SEQ server as requested by security team , what are the steps?

**Comment by nblumhardt** [comment]
Hi John, thanks for dropping us a line.

IIRC these are disabled by default on recent/patched Windows servers, but otherwise, group policy or registry edits can disable them: https://www.google.com/search?q=disable+legacy+tls+versions

OpenSSL can be used to probe supported TLS versions: https://www.google.com/search?q=probe+supported+tls+versions+with+openssl

Let me know if this helps,
Nick

**Comment by nblumhardt** [comment]
Hi John, just checking in - were you able to resolve this? Thanks!

**Comment by c0shea** [comment]
If you're running on Windows Server, you can also use the [IIS Crypto](https://www.nartac.com/products/iiscrypto) tool to disable insecure protocols and cipher suites on the server.

**Comment by KodrAus** [comment]
Thanks for the note @c0shea :+1: That should help anyone else finding this issue via a search. I'll go ahead and close this one now since it's not really Seq specific, but the issue is still discoverable via search so is still useful in that state.
