### ISSUE TITLE
Parameterized alert notifications

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#566]
Alerts can be channeled through apps like _Email+_ and _Slack_. Rather than create a whole new app instance for each destination email address or channel, it'd be great if these can be configured along with the alert.

**Edit:** [RFC](https://github.com/datalust/seq-tickets/blob/master/rfcs/0642-app-invocation-parameters.md)

**Comment by nblumhardt** [comment]
I think #565 is going to be the focus for 4.1; moving this to 4.2.

**Comment by nblumhardt** [comment]
Circling back around to this, I think there are two parts.

First, when the alert is created, a set of properties could be associated with the alert. E.g. an alert might have `Email = 'nb****@datalust.co'` and/or `Priority = 'High'`.

When the alert is triggered, these would be attached to the generated event, and therefore passed through to the app used for notifications.

On the app side, there are two competing implementation options.

Currently, apps like _Email+_ support binding of various fields (like the email subject or body) through their own built-in templating.

 * Pro - it's efficient; any app that needs to establish and maintain expensive connections or other state will be able to handle event parameters more efficiently if the same running software object/process handles multiple parameterised events
 * Con - it requires the app to opt in, by deciding which fields can support templating, and applying the template to the event at runtime
 * Con - doesn't support binding of non-string properties (e.g. checkboxes)
 * Con - a standard approach to templating could be provided for C# apps, but new templating implementations would have to be devised for other languages

Alternatively, the templating could be applied by Seq, so if an app property like `To:` could be bound to an event property at configuration time, and Seq would create running objects/processes on the fly with their properties pre-bound to the values from the event causing activation:

 * Pro - would work with all existing apps
 * Pro - could support all data types
 * Pro - would work transparently for all implementation languages
 * Con - the templating mechanism would appear inconsistent when used alongside existing templating mechanisms like the Handlebars templates implemented by _Email+_
 * Con - it could be prohibitively expensive to start a new app object/process for every incoming event

**Comment by KodrAus** [comment]
We've got some progress on paramaterised alert notifications to share!

When configuring an app instance, an admin can mark any setting as _allowing overrides_. Then, when configuring an alert or sending an event to an app instance, any user can then provide their own values for these settings, or use whatever the admin entered as a default value.

Setting overrides are handled by Seq, so existing apps don't need to be updated to support overrides. Overrides do come with performance implications though, because each invocation of an app using overridden settings means starting a new OS process, passing the relevant events along and then tearing it down. App instances that don't allow overrides will share a single process. This shouldn't really be noticeable if an app is only invoked once every few minutes, otherwise you can use a specific app instance for alerts expecting heavy traffic with no overrides enabled.

# Enabling and disabling setting overrides

![enable-disable-overrides](https://user-images.githubusercontent.com/6721458/34549528-eaa21754-f154-11e7-9c9c-45dc5e6ff128.gif)

# Overriding settings when configuring an alert

![alert-overrides](https://user-images.githubusercontent.com/6721458/34549554-460c13f6-f155-11e7-9f80-b5874cd2f036.gif)

# Overriding settings when sending an event to an app instance

![send-to-app-overrides](https://user-images.githubusercontent.com/6721458/34549558-516892d8-f155-11e7-8127-a34f49ee944f.gif)
