### ISSUE TITLE
Tag signals are not added to URL in order selected

### ISSUE THREAD

**Issue by laurencee** [datalust/seq-tickets#686]
**Bug description:**

For tag signals, the order in which you select them matters as it changes how they display on the log events. Currently tag signals that belong to a group are always added to the url in ascending numerical order.

**Reproduction steps**
1. Create 2 tag signals and group them together
2. Select the tags in order A -> B
3. Copy the url (url 1)
4. Select the tags in order B -> A
5. Copy the url (url 2)

**Expected**

Url 1 and Url 2 will retain the order in which the tags were selected.

**Actual** 

Url 1 and Url 2 will display the tags in the same order.

**Comment by laurencee** [comment]
Thought I'd give this one a bump as a person on my team re-discovered it again today but I forgot I had already posted this issue.

**Comment by nblumhardt** [comment]
Thanks Laurence, we'll keep this one on the radar.

**Comment by nblumhardt** [comment]
Thanks again for raising this; because tags from multiple signals are combined when viewing the logs, and those may have contradictory orderings, this is a bit more complex than it appears at first glance.

I think this one will stick in the back of our minds, but we're not likely to be able to address this in the near future so we'll close this for now.
