### ISSUE TITLE
Seq crashes in Docker

### ISSUE THREAD

**Issue by qadmium** [datalust/seq-tickets#702]
After ~1 min of work Seq crashes with: 

`mdb.c:5276: Assertion 'NUMKEYS(mp) > 1' failed in mdb_page_search_root()`

DB contains logs for 24 hours. Can't find something more useful in logs. Looks like something happened with LMDB

**Comment by nblumhardt** [comment]
Thank you for the report, much appreciated.

This looks like: http://www.openldap.org/its/index.cgi/Software%20Bugs?id=8336 - the Ubuntu 16.04 image that the preview container is based on, packages 0.9.17.

We're just a few weeks away from a new version of the Docker image using a new, native event storage layer instead of LMDB, but, we're planning to continue basing the internal metastore (users/api keys/retention policies, etc.) on LMDB, so we'll move forward before RTM.

**Comment by qadmium** [comment]
Workaround: remove extent data

**Comment by nblumhardt** [comment]
This should no longer occur in the latest datalust/seq image
