### ISSUE TITLE
v5 AD integrated link

### ISSUE THREAD

**Issue by nskerl** [datalust/seq-tickets#766]
Did something change in v5 regarding the AD integrated link? It appears it is hidden for non-IE browsers.  In v4 this link is visible in Chrome and FF as well.  

Authentication seems to work fine if I hit the `http://localhost:5341/integrated` link directly, so i'm not sure why it would be hidden.

![image](https://user-images.githubusercontent.com/782187/49043608-6fe22680-f180-11e8-9de0-ed2628235100.png)

**Comment by nblumhardt** [comment]
Hi Nathan; interested to know that this impacts you; we went through testing integrated auth in v5 and were unable to get a satisfactory experience out of browsers other than IE (they'd end up asking for a username/password, anyway, instead of automatically signing the user in as IE would). Was this not the case in your environment? Thanks!

(We included a small note about this in the upgrade guide, but it was easily missed - https://docs.getseq.net/docs/upgrading-from-seq-42#section-browser-and-platform-prerequisites)

**Comment by nskerl** [comment]
We did have to coerce Firefox into playing nice with NTLM on intranet sites by toggling a few configs (see below).  This is not a huge impact to us. We were accustomed to the link (same in Octopus) but we can deal with it if you found it spotty between browsers.

I'm pretty sure this was the flag we flipped. I can research if you need more info.

![image](https://user-images.githubusercontent.com/782187/49101761-d83a1200-f22b-11e8-888b-4ab6244dc03f.png)

**Comment by nblumhardt** [comment]
Ah, interesting, thanks. We'll take another look, this might have been what tripped us up.

**Comment by vlm---** [comment]
Integrated link works fine in our domain (SSO with smart cards, no passwords) with Chrome without any special settings in browser. I was curious that I couldn't find it after the upgrade to v5. Maybe you can put it back with some warning about the possibility of bad experience.

**Comment by pcoombe** [comment]
ah just came looking into why the link disappeared.
yes please bring it back

to make FF behave, just use the settings supplied above
in Chrome you probably have to add the url to intranet zone, if you dont have SSO

**Comment by nblumhardt** [comment]
5.1.2894-pre re-enables the link; it would be great if it sees some wider testing again before RTM, just to make sure everything is now covered.
