### ISSUE TITLE
Question: seq on nanoserver based docker image possible?

### ISSUE THREAD

**Issue by penenkel** [datalust/seq-tickets#785]
AFAIK you have provided two (experimental) docker images for seq. One for linux containers and one for windows containers. The later one is based on servercore. Is there a reason for that? Why not nanoserver?
To my, perhaps naive, understanding, if seq runs under Linux, it should also be possible to run it on nanoserver images.

**Comment by nblumhardt** [comment]
Hi @penenkel;

The `datalust/seq` Linux-based container is currently in production; the `datalust/seq-windows` one stalled at the "experimental" phase unfortunately, and it's not likely we'll be able to move this forward in the immediate future. The [Windows Dockerfile](https://github.com/datalust/seq-docker-windows) is public, however, so you can build a container using the latest MSI if you need one.

My memory is a little hazy, but IIRC, the nano images don't contain ESENT, which Seq 5 still uses for configuration data (and compatibility with old storage extents).

Hope this helps,
Nick

**Comment by penenkel** [comment]
Hello Nick, thanks for your response.

If I'm understanding you correctly the seq binaries for Windows (i.e. the MSI) need ESENT, which is not part of nano images, thus the "easy" way (i.e. to simply install the default MSI on a nano image) is out.

But my reasoning is this: 
According to this [article](https://nblumhardt.com/2018/03/from-netfx-to-core/) you already have an alternative for ESENT with LMDB. Which made the linux version possible in the first place. Doesn't that mean that you have a fully cross platform capable (.NET Core based) build of seq, that by definition should also run on nano images?

I'm guessing I'm missing some crucial point here.

**Comment by nblumhardt** [comment]
Thanks for the follow-up; yes, in theory we could run the LMDB document store on Windows, but to maintain continuity for existing installs, we've chosen to stick with ESENT for the current Windows build.

Allowing LMDB to be selected as an option is an interesting possibility, but it doesn't currently align with anything on our roadmap, so isn't likely to be possible in the immediate future. If it's highly-desirable in your environment that would be great data for us to have - thanks!

**Comment by nblumhardt** [comment]
Closing, but please feel free to jump back in if there's any more to add on this. Thanks!

**Comment by penenkel** [comment]
Sorry for the late response. 
Basicly it would just be "nice to have". At the moment I do not have any pressing need for it.
Thanks for your help.

**Comment by mloskot** [comment]
Since Windows container base image have been improved over last 1-2 years ([1](https://techcommunity.microsoft.com/blog/containers/reducing-the-size-of-windows-server-container-images-%e2%80%93-part-2/3741795), [2](https://techcommunity.microsoft.com/blog/containers/continuing-improvement-to-windows-server-containers-and-the-upcoming-changes/3816701), [3](https://techcommunity.microsoft.com/blog/itopstalkblog/new-windows-container-content-on-microsoft-learn/3835027), etc.) - NanoServer and ServerCore are in a bit different place now than 5-6 years ago - would you consider unarchiving https://github.com/datalust/seq-docker-windows, opening it for contributions and publishing up to date images to https://hub.docker.com/r/datalust/seq-windows ?

**Comment by KodrAus** [comment]
Hi @mloskot we don't have any plans at this stage to revive a Windows container offering, but it's something to keep on our radar.

**Comment by mloskot** [comment]
@KodrAus Thank you, I understand. 🤞
