### ISSUE TITLE
Secure the API during the start-up process on first run

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#791]
It's unclear exactly how this would work, but in containerized environments it would be desirable to configure settings such as basic or AAD authentication during container start-up, rather than afterwards via the API (which can be difficult to sequence into the deployment process).

Via: https://docs.getseq.net/v5.0/discuss/5c531e11d7a54f004b47f9b3

**Comment by HakanL** [comment]
Maybe a "startup-json" file that can be passed in as a parameter (or just located on the data volume)? That json file can have the API requests to configure the different options (including the theme)

**Comment by nblumhardt** [comment]
This mechanism should ideally also basic configuration such as retention policies and signals.

**Comment by dazinator** [comment]
One idea might be, on startup of the application when building the `IConfiguration` - include an additional json settings file e.g "foo.settings" from the persistent storage directory if it exists. Once the IConfiguration is built to include this additional settings file, you can check for any additional keys and do any one time processing if they exist and delete the file afterwards if necessary.

Then in order to "prime" a container, it would just be a matter of mounting a volume that has this file present. The volume can be prepared in advance.

I'm assuming you might want to process this settings file and delete it afterwards because things like passwords etc might need to be present in plain text, and I guess seq will want to read those settings, configure stuff, then save it back to its own config file in an encrypted form, and delete the non-secure file.

Config hierarchy would be something like:

1. Local appsettings.json
2. seq's persisted settings.json file from storage directory.
3. additional one-time config file processed on startup and then deleted.

**Comment by CrossBound** [comment]
I agree that a config file makes sense. The other thing to keep in mind is that in Kubernetes the container/pod could get restarted at any time so deleting the file after the system is primed would be necessary if using a statefulset. 

Some things I'd like to be able to set during initialization include:
- signals
- apps
- nuget feeds (file system)
- api keys
- retention policies

As an aside... if I backup an already configured system does the backup include all the items in my list above? If so I might could just restore my backup after the first initialization of the container.

**Comment by nblumhardt** [comment]
Hi @CrossBound - thanks for the notes 👍 

> if I backup an already configured system does the backup include all the items in my list above?

Yes, all of those items are included in Seq backups.

**Comment by nblumhardt** [comment]
Hi all 👋 ; we're going to keep this to the original purpose of the ticket, since the scope of what may need to be configured on first-run is wide. In the first cut, we think the recipe is:

 1. Secure the HTTP API with a provided username/password on first run
 1. Complete configuration using the API and an API client (such as _Seq.Api_ or `seqcli`) once the container is up (e.g. to add API keys, retention policies, signals, to switch auth provider, and so on)

Invoking the configuration script or program for step (2) will still be a task for the orchestrator.

This solves the problem of the API starting up unsecured over a new container instance, which is valuable enough to address on its own; we can investigate options for simplifying the subsequent configuration in another ticket. Feedback welcome as always, of course :-)

**Comment by CrossBound** [comment]
Will environment variables be the only option or can we use files (e.g. kubernetes secrets mounted into a volume)?

**Comment by nblumhardt** [comment]
Hi @CrossBound - thanks for the follow-up.

It would be possible to set these values in the _Seq.json_ file through a CLI command in the container, or by pre-populating the `/data` volume.

The values will be read from the `firstRun.adminUsername` and `firstRun.adminPassword` fields in _Seq.json_ if present.

I'm not sure how tricky this would be to get going in Kubernetes, but keen to work through it with you if it sounds feasible.
