### ISSUE TITLE
Attach additional properties to events from custom inputs (e.g. health checks, GELF endpoints)

### ISSUE THREAD

**Issue by CrossBound** [datalust/seq-tickets#832]
Would really like to see an additional option with the new Health Check feature. I'd like to be able to put custom properties/tags on the events input from the Health Check app just like you can with API Keys. 

For my API keys I've been adding an Environment (Production, Development, etc.) and System property. I'd like to be able to do the same for each health check instance.

Otherwise this is a great feature.

Thanks

**Comment by nblumhardt** [comment]
Thanks for the suggestion 👍

**Comment by nblumhardt** [comment]
Just to add a bit more background on this; the design decision we need to make is whether to allow an input to be associated with an API key instead of the default _None_ key we currently use, or, we generalize on the notion of an "input" and make both plug-in apps, and API keys as they exist today, into particular kinds of inputs.

The first option's a lot faster to implement, but a bit logically "fishy" as there really isn't any API involved, let alone a key :-)

The second option is a bit more complex, and needs more work, but might stand the test of time better as new kinds of inputs come into the picture.

We're ruling out a third option, which would be to build this directly into the "apps" screen or the app itself, since we'll inevitably end up replicating other features that currently exist in API keys, like rate counters, input filters, and level controls.

Just to complicate things a little more, at some point we'll want custom inputs to be able to receive payloads tagged with an API key as well.

**Comment by CrossBound** [comment]
I was going to vote for the second option, but the more I think about it the more I realize I'm not sure that will entirely be best. One problem is that I initially was thinking you wouldn't need to apply any type of security to the "app" input, but then realized that inputs such as GELF input or SYSLOG will be coming in through an app, so for those inputs it might still be nice to treat it as a sort-of secondary API if you will and require the client to supply some form of authentication. 

A problem with enforcing security for the app input is that (in the case of syslog or gelf) the client probably has no notion of a security interface that it can implement and probably has very limited extensibility to enable that.

With all of that said, probably the second option is better: each input (app or api) is treated as an "input" and an API Key is simply one of the types of inputs.

**Comment by nblumhardt** [comment]
![image](https://user-images.githubusercontent.com/342712/81247485-78b97600-905d-11ea-8500-70c81bc1e12f.png)

We took the second approach - API keys, unauthenticated HTTP, custom inputs, and app diagnostics, are all types of input. Some nice unification and better UX coming out of this. Thanks for all the _input_! ;-)

**Comment by CrossBound** [comment]
Excellent, excited to see this. Will this be a version 6 feature?

**Comment by nblumhardt** [comment]
Hi @CrossBound - yes; new preview on the way very shortly :-) 👍

**Comment by nblumhardt** [comment]
This is out in the latest 2020.1 preview (4014-pre) - all feedback appreciated!

CC @tsimbalar
