### ISSUE TITLE
When a storage path is specified in the installer, send internal logs there also

### ISSUE THREAD

**Issue by caioproiete** [datalust/seq-tickets#872]
Hello hello, small bug report observed with Seq v5.1.3118:

When installing Seq, I've set my **Storage path** to `D:\Seq`, and the `Seq.json` config file along with `Documents` and `Extents` folders are correctly stored under `D:\Seq`.

![image](https://user-images.githubusercontent.com/177608/60019763-ff8f7b00-9664-11e9-8b3d-db76cf21d33d.png)

However, logs are always written to `C:\ProgramData\Seq\Logs` with this path being hard-coded in the `Seq.json` file.

```
  ...
  "diagnostics": {
    "internalLogPath": "C:\\ProgramData\\Seq\\Logs",
     ...
  },
  ...
```

The expectation was that logs would be written under the storage path configured, i.e. `D:\Seq\Logs` in this case.

Manually updating `Seq.json` and restarting the service is a workaround.

**Comment by nblumhardt** [comment]
Hi Caio, thanks for the note!

This is "by design," (noted at the bottom of [this doc](https://docs.datalust.co/docs/storage-paths-and-urls),) though unfortunately it can be a bit surprising.

There were a few reasons for doing this - originally, not all Seq commands were storage-path-aware, incorrectly-configured storage paths couldn't be logged, and support was tricky if the admin inheriting a Seq server was unsure of the storage path.

I don't think any of these reasons would push us in this direction anymore, so we'll discuss changing the behavior of the installer, but I'll need to dig around to determine the effects.

**Comment by nblumhardt** [comment]
Thanks again for reporting this one, Caio. We're going to stick with the current behavior, but could revisit this down the track.
