### ISSUE TITLE
Server timestamp with apikey

### ISSUE THREAD

**Issue by imtrobin** [datalust/seq-tickets#887]
Hi, I'm testing Seq, with Postman POST raw json, I have setup an apiKey, butit still expects the client to have timestamps

e.g POST body 
{"@mt":"Hello, {User}","User":"alice"}
{"@mt":"Hello, {User}","User":"bob"}

fails
{
    "Error": "The event on line 1 does not carry an `@t` timestamp property."
}

Shouldn't server timestamps be the default? The client timestamp can't be trusted

**Comment by nblumhardt** [comment]
Hi! Thanks for checking out Seq :-)

Because batching is used extensively with the HTTP API, server timestamps don't usually have enough resolution to work nicely here (all events in, say, a five second batch, end up with the same timestamp).

(We've considered falling back to using a server timestamp in this scenario, but all environments we're aware of that can format and send JSON via HTTP are adequate to embed an `"@t":"2019-09-10T12:34Z"` style timestamp, so it seems like implementing the fallback will just degrade usability without saving substantial work.)

What kind of client library (Serilog?) do you plan to use with Seq?

Best regards,
Nick

**Comment by imtrobin** [comment]
Good point. I'm planning to aggreate logs from different systems in C++, C#, so I might use my own with HTTP API since I don't think there is a good C++library and I already have own logging.

**Comment by nblumhardt** [comment]
Great! Good luck with it - and please get in touch if there's anything more we can help with :+1:
