### ISSUE TITLE
Azure Active Directory documentation out of date

### ISSUE THREAD

**Issue by worldspawn** [datalust/seq-tickets#900]
https://docs.datalust.co/docs/azure-active-directory

After 3.1 the guidance refers to a bunch of stuff that doesn't exist. There are no "reply urls", there is no "Keys".

Also this page -> https://docs.datalust.co/docs/storage-paths-and-urls under Uninstalling the service says: 

>Uninstalling the Seq service does not have any impact on the stored events or configuration - only the Windows service entry.

Upon reinstall I lost all authentication configuration, all api keys, everything actually.

**Comment by nblumhardt** [comment]
Hi Sam, thanks for the note RE AAD docs; we have it on an internal "to do" list, but this ticket will help us get moving along :-)

The data loss on reinstall will be due to your old storage path not being the same as the default one - if you still have the machine, we can help you figure it out and get the old instance back up and running.

(The MSI installer only touches executables in `C:\Program Files\Seq`, while all configuration/event data is by default in `C:\ProgramData\Seq`. After a reinstall, the service will point to that default location, unless you give the path to your existing data in the post-install configuration dialog or reconfigure it after installation.)

Hope this helps,
Nick

**Comment by worldspawn** [comment]
Yeah I stopped, uninstalled and reinstalled to another folder. I then tried repeating that, pointing back to the old storage location but my old config did not come back. 

It was our only dev log server and only injesting 3 api keys so we just remade it. 
Luckily we found the old azure creds in a lastpass entry so we're back up.

**Comment by nblumhardt** [comment]
Thanks for the follow-up. Glad you're up and running 👍

**Comment by nblumhardt** [comment]
Done! https://docs.datalust.co/v2020.1/docs/azure-active-directory
