### ISSUE TITLE
When filtering API keys, match if `TokenPrefix` is a prefix of the search string

### ISSUE THREAD

**Issue by Suchiman** [datalust/seq-tickets#905]
If you copy and paste a full API key into the search box, then it will yield no results, you have to backspace until you reach the truncation limit before it starts matching.
![image](https://user-images.githubusercontent.com/7110884/68678431-37d51e80-055e-11ea-8ed7-17bb3ef8efb3.png)

**Comment by nblumhardt** [comment]
Interesting! Thanks for the note, @Suchiman . I guess that we could check whether `TokenPrefix` is a prefix of the search text - would be nice in this case, and since they're generally random values, it's unlikely to cause undesirable mismatches.

(We can't match the full token value because it's irretrievably hashed; we could hash the search text and make a comparison on the server, but currently filtering is purely client-side, and opening this up in the API could also have security implications, or would at least need consideration from that angle.)
