### ISSUE TITLE
Seq 5.1.3118 refuses to install on Windows Server 2012

### ISSUE THREAD

**Issue by IanYates** [datalust/seq-tickets#913]
Releated to end note in issue #737 where a blocker was put in to restrict to 2012 R2 / Windows 8.1 or newer.
However on the server I'm looking at right now, it's a 2012 server that's quite happily running 5.0.2817 .

Can the block be changed to Server 2012 rather than 2012 R2 (and thus Windows 8.0 instead of 8.1)?

Not a huge issue really but I thought I'd ask about the discrepancy since a lot of products assume everyone's on Windows 8.1 when the user had 8.x, due to it being a free update from 8.0.  That free upgrade, unfortunately, was not the case for Server 2012 & 2012 R2.

Thanks :)

**Comment by nblumhardt** [comment]
Hi! Thanks for the note, Ian.

I would guess that, to get Seq running on 2012, you have `storage.preferredEngine` explicitly set to `LMDB` or `ESENT`? (You can run `seq config` to check this out.) Otherwise, IIRC, Seq will fail to start, which is suboptimal UX, of course :-)

We're keen to help for as long as Seq continues to work on that version, but as we don't test on it, and major new features won't work there (in particular, the new storage engine), I don't think we should change the installer prerequisites. XCOPYing the Seq program files from a supported machine to the unsupported one will do the job, though.

Let me know if this helps!

Nick

**Comment by nblumhardt** [comment]
In v6 we're finally completely deprecating ESENT event storage in favour of a complete migration to the newer native engine, which won't run on 2012. I'll close this as I don't think we'll be able to support 2012 (non-R2) in future, but still keeping this one in mind.

**Comment by IanYates** [comment]
Thanks Nick.  We'll stick with the older release on that server - not a huge issue.  It was a server upgraded from 4.x so would've still been using ESENT (I wouldn't have chosen an engine specifically but just left it to march on using what it had)

I suspect it wouldn't be worth your time and effort to try to support 2012 as many other vendors have also reached the same conclusion to the point where we'll hopefully have the remaining holdouts drop it soon in favour of just moving to 2016/2019.
