### ISSUE TITLE
+X More

### ISSUE THREAD

**Issue by chrisfink** [datalust/seq-tickets#943]
Is it possible to keep the signals menu expanded without having to click the +X More link at the bottom of the signals? I would find this very useful to toggle this option since all of our signals fit on the page and clicking the more link is just an extra step.

Thanks

**Comment by nblumhardt** [comment]
Hi Chris, thanks for the note.

Which signals are shown depends on the "workspace" you're in; by default, it will be called "Personal" and appear in the top right of the Seq navbar.

If you click "Personal" it should pop out a small window, with a drop-down arrow at the top right. If you expand the menu, you can de-select "Make default" and this should update your preferences.

Then, click "Personal" again, and choose the "x" to close it.

Now, you'll always see all signals (and dashboards) - Seq will no longer open the workspace by default.

Let me know if this helps!

Nick

**Comment by chrisfink** [comment]
Hi Nick,

Is there a way to keep the signal menu expanded by default instead of
always having to click the + more link at the bottom of the menu?

Thanks again for your help,
Chris

**Comment by nblumhardt** [comment]
Hi Chris - not sure I understand - that's the result of following the steps in my answer above. Let me know if I've misunderstood.

Best regards,
Nick

**Comment by nblumhardt** [comment]
Hi Chris, re-reading, I'm not sure my initial answer was clear, rephrasing :-) -

 * "+X more" is shown when your Seq view is within a workspace; workspaces are used to reduce the number of signals and other items shown, in order to create a more focused experience in particular contexts
 * To get rid of it, you can close the workspace from the workspaces drop-down (usually shown as "Personal" in the title bar, unless you've created custom workspaces)
 * To stop the workspace reopening by default, you can deselect this option from the workspace's context menu

Definitely an experience we could streamline, and we're giving more though to it. Closing in an issue-tracker review, but please jump back in if I've misunderstood, or if you need any more info.

Best regards,
Nick
