### ISSUE TITLE
Signal from nested Object

### ISSUE THREAD

**Issue by SeriousM** [datalust/seq-tickets#946]
When we're logging, we add a structure of metadata to each logline.
We would like to have a way to define that a signal is based on a nested property in this structure in contrast to first-level properties.

How can we achieve this?

**Comment by nblumhardt** [comment]
Hi Bernhard,

Just copying my reply from your support forum post; I'll close this ticket and follow up via the forum so that we keep the discussion in one place :-)

--

If an event has property, say, `User`, which is an object, e.g. `{"Id": "user-1", "Username": "alice"}`, then search expressions can just dot through to those subproperties, e.g.:

```
User.Username = 'alice'
```

With a search like this in the search box, pressing >> will add that condition to a signal.

**Comment by SeriousM** [comment]
Just as cross-reference: https://docs.datalust.co/discuss/5e5e1dab27bf6200262e0735
